# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    salavert.twig.time_ago:
        class: Salavert\Twig\Extension\TimeAgoExtension
        arguments: ["@translator"]
        tags:
            - { name: twig.extension }

    app.tweet_manager:
        class: AppBundle\Manager\TweetManager
        arguments:
          - "@doctrine.orm.entity_manager"
          - "%app.tweet.nb_last%"

    app.email_messenger:
        class: AppBundle\Messenger\EmailMessenger
        arguments:
          - "@mailer"

